### ISSUE TITLE
Suggestion to Rename the Default Branch from 'master' to 'main

### ISSUE THREAD

**Issue by dotshix** [LuisMInfante/Unforgotten#1]
Dear Unforgotten Maintainers,

I hope this message finds you well. I'm writing to express a suggestion regarding the naming convention used for the default branch in your GitHub repository.

In recent years, there's been a significant movement within the tech community towards more inclusive language. Part of this effort includes moving away from terms with potentially oppressive connotations. Many organizations and projects have started renaming their default branches from "master" to "main", a change that GitHub itself endorses and facilitates.

I believe that adopting this change for Unforgotten would be a positive step towards greater inclusivity. Here's a guide from GitHub on [how to rename a branch](https://github.com/github/renaming).

If there's any way I can assist in this process, please let me know. I understand that such changes require time and effort, and I'm more than willing to help.

Thank you for considering this suggestion. Good luck on your project.

Best regards,
shux

**Comment by psmit03** [comment]
wow, love pharit
